### ISSUE TITLE
Doesn't work on Windows 7

### ISSUE THREAD

**Issue by helarqjsc** [plexus/chestnut#134] opened 2015-07-12 14:51 UTC
When I start REPL and type `(run)`, I get the following error:
```
three-html-boxes.server=> (run)

InvalidPathException Illegal char <:> at index 2: /C:/github/three-html-boxes/resources/index.html  sun.nio.fs.WindowsPathParser.normalize (WindowsPathParser.java:182)
```
I get the same error in git bash and regular cmd. Any ideas on how to fix that?

**Comment by plexus** [comment] 2015-07-12 14:56
closing as it's a duplicate of an existing issue.

**Closed by plexus** 2015-07-12 14:56 UTC

**Comment by helarqjsc** [comment] 2015-07-12 14:59
My bad, it is indeed the same issue as #104
