### ISSUE TITLE
How to update a chestnut project?

### ISSUE THREAD

**Issue by jmatsushita** [plexus/chestnut#115] opened 2015-04-10 08:45 UTC
Hi there,

I've been wondering whether there is a recommended way to upgrade a chestnut project apart from diffing?

Cheers,

Jun

**Comment by rbxbx** [comment] 2015-06-25 19:02
Also curious about this :)

**Comment by kevincolyar** [comment] 2015-07-02 22:29
:+1:

**Comment by plexus** [comment] 2015-07-07 09:20
Generate a project with the old version and one with the new, diff the two, apply changes to your project.

See also the bottom part of my explanation [here](http://chestnut.aren.io/t/faq-will-chesnut-support-reagent-quiescent-rum-etc/22)

**Comment by plexus** [comment] 2015-07-09 14:21
There's a forum post with more info, closing this as it's not a bug. http://chestnut.aren.io/t/how-to-upgrade-from-0-7-to-0-8/47

**Closed by plexus** 2015-07-09 14:21 UTC

**Comment by rbxbx** [comment] 2015-07-09 22:19
Thanks @plexus! Maybe we can work on smoothing this out in the future, but it seems reasonable for now. Cheers.
