### ISSUE TITLE
Clarification on cljsbuild configs

### ISSUE THREAD

**Issue by afhammad** [plexus/chestnut#149] opened 2015-08-10 18:00 UTC
There seems to be several cljsbuild configs in the template, both in project.clj and dev.clj. can someone clarify when is each used? Also is there a DRYer approach (for example do i have to set externs on all of them)?

It might also explain why running `lein repl` and calling `(run)` results in this exception while using `lein cljsbuild auto app` works.

Compiling "resources/public/js/app.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:src/cljs/eztz/core.cljs
 at clojure.core$ex_info.invoke (core.clj:4403)
    cljs.compiler$compile_file$fn__5026.invoke (compiler.clj:1142)
    cljs.compiler$compile_file.invoke (compiler.clj:1105)
    cljs.compiler$compile_root.invoke (compiler.clj:1177)
    cljs.closure$compile_dir.invoke (closure.clj:378)
    cljs.closure$eval5442$fn__5443.invoke (closure.clj:418)
    cljs.closure$eval5378$fn__5379$G__5369__5386.invoke (closure.clj:325)
    cljs.closure$eval5429$fn__5430.invoke (closure.clj:432)
    cljs.closure$eval5378$fn__5379$G__5369__5386.invoke (closure.clj:325)
    clojurescript_build.core.CompilableSourcePaths/fn (core.clj:18)
    clojure.core$map$fn__4245.invoke (core.clj:2557)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:484)
    clojure.core$seq.invoke (core.clj:133)
    clojure.core$apply.invoke (core.clj:624)
    clojure.core$mapcat.doInvoke (core.clj:2586)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojurescript_build.core.CompilableSourcePaths._compile (core.clj:18)
    cljs.closure$build.invoke (closure.clj:1446)
    clojurescript_build.core$build_source_paths_STAR_.invoke (core.clj:150)
    figwheel_sidecar.auto_builder$default_build_options$fn__16219.invoke (auto_builder.clj:66)
    figwheel_sidecar.auto_builder$warning$fn__16216.invoke (auto_builder.clj:61)
    clojurescript_build.auto$time_build$fn__16029.invoke (auto.clj:55)
    clojurescript_build.auto$after$fn__16035.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__16035.invoke (auto.clj:64)
    clojurescript_build.auto$after$fn__16035.invoke (auto.clj:64)
    clojurescript_build.auto$error$fn__16038.invoke (auto.clj:71)
    clojurescript_build.auto$before$fn__16032.invoke (auto.clj:60)
    clojurescript_build.auto$make_conditional_builder$fn__16050.invoke (auto.clj:103)

**Comment by slester** [comment] 2015-08-10 18:25
Duplicate of #133.

**Comment by plexus** [comment] 2016-01-03 19:22
This has now been addressed in the [v0.9 branch](https://github.com/plexus/chestnut/tree/v0.9), we use the new `figwheel-sidecar.repl-api`, which handles reading the config out of `project.clj`, so we no longer have to duplicate it.

**Closed by plexus** 2016-01-03 19:22 UTC
Labels: bug, duplicate
