### ISSUE TITLE
using the latest version of chestnut  template caused  'No such namespace: ' error when running (run)

### ISSUE THREAD

**Issue by tokomakoma123** [plexus/chestnut#91] opened 2015-02-01 12:47 UTC
I created a project using the latest version of chestnut template (v0.7.0-SNAPSHOT-20150103) caused  'No such namespace'  error when I ran 'lein repl'  and (run). 

I made project by 'lein new chestnut test-app' and then 'lein repl' & '(run)' caused an exception.
The error means env/dev/cljs/test_app/main.cljs could not find the app namespace test-app.core.

```shell
$ lein repl
nREPL server started on port 59271 on host 127.0.0.1 - nrepl://127.0.0.1:59271
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.7.0-alpha5
Java HotSpot(TM) 64-Bit Server VM 1.7.0_25-b15
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

test-app.server=> (run)
Figwheel: Starting server at http://localhost:3449
Figwheel: Serving files from '(resources)/public'
2015-02-01 21:35:02.346:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-02-01 21:35:02.396:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:10555
Starting web server on port 10555 .
#<Server org.eclipse.jetty.server.Server@6123f874>
test-app.server=> Compiling "resources/public/js/app.js" from ["env/dev/cljs" "src/cljs"]...
Compiling "resources/public/js/app.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:env/dev/cljs/test_app/main.cljs
               core.clj:4577 clojure.core/ex-info
           compiler.clj:1040 cljs.compiler/compile-file
           compiler.clj:1070 cljs.compiler/compile-root
             closure.clj:353 cljs.closure/compile-dir
             closure.clj:393 cljs.closure/eval4758[fn]
             closure.clj:301 cljs.closure/eval4694[fn]
             closure.clj:407 cljs.closure/eval4745[fn]
             closure.clj:301 cljs.closure/eval4694[fn]
                 core.clj:18 clojurescript-build.core.CompilableSourcePaths/fn
               core.clj:2612 clojure.core/map[fn]
             LazySeq.java:40 clojure.lang.LazySeq.sval
             LazySeq.java:49 clojure.lang.LazySeq.seq
                 RT.java:485 clojure.lang.RT.seq
                core.clj:135 clojure.core/seq
                core.clj:626 clojure.core/apply
               core.clj:2650 clojure.core/mapcat
             RestFn.java:423 clojure.lang.RestFn.invoke
                 core.clj:18 clojurescript-build.core/clojurescript-build.core.CompilableSourcePaths
            closure.clj:1065 cljs.closure/build
                core.clj:150 clojurescript-build.core/build-source-paths*
                 auto.clj:86 clojurescript-build.auto/warning[fn]
                 auto.clj:55 clojurescript-build.auto/time-build[fn]
                 auto.clj:64 clojurescript-build.auto/after[fn]
                 auto.clj:64 clojurescript-build.auto/after[fn]
                 auto.clj:64 clojurescript-build.auto/after[fn]
                 auto.clj:71 clojurescript-build.auto/error[fn]
                 auto.clj:60 clojurescript-build.auto/before[fn]
                auto.clj:103 clojurescript-build.auto/make-conditional-builder[fn]
               core.clj:6611 clojure.core/mapv[fn]
   PersistentVector.java:332 clojure.lang.PersistentVector.reduce
               core.clj:6513 clojure.core/reduce
               core.clj:6611 clojure.core/mapv
                auto.clj:180 clojurescript-build.auto/autobuild*[fn]
                auto.clj:176 clojurescript-build.auto/autobuild*[fn]
          ioc_macros.clj:940 clojure.core.async.impl.ioc-macros/run-state-machine
          ioc_macros.clj:944 clojure.core.async.impl.ioc-macros/run-state-machine-wrapped
               async.clj:362 clojure.core.async/ioc-alts![fn]
               async.clj:231 clojure.core.async/do-alts[fn]
            channels.clj:262 clojure.core.async.impl.channels.ManyToManyChannel/fn
                 AFn.java:22 clojure.lang.AFn.run
ThreadPoolExecutor.java:1145 java.util.concurrent.ThreadPoolExecutor.runWorker
 ThreadPoolExecutor.java:615 java.util.concurrent.ThreadPoolExecutor$Worker.run
             Thread.java:724 java.lang.Thread.run
Caused by: clojure.lang.ExceptionInfo: No such namespace: test-app.core at line 1 env/dev/cljs/test_app/main.cljs
               core.clj:4577 clojure.core/ex-info
            analyzer.clj:299 cljs.analyzer/error
            analyzer.clj:296 cljs.analyzer/error
           analyzer.clj:1104 cljs.analyzer/analyze-deps
           analyzer.clj:1289 cljs.analyzer/eval3156[fn]
            MultiFn.java:251 clojure.lang.MultiFn.invoke
           analyzer.clj:1624 cljs.analyzer/analyze-seq
           analyzer.clj:1711 cljs.analyzer/analyze[fn]
           analyzer.clj:1704 cljs.analyzer/analyze
            compiler.clj:948 cljs.compiler/compile-file*[fn]
            compiler.clj:906 cljs.compiler/with-core-cljs
            compiler.clj:927 cljs.compiler/compile-file*
           compiler.clj:1034 cljs.compiler/compile-file
```

**Comment by samedhi** [comment] 2015-02-04 22:02
This seems similar to #83 . Are you perhaps calling 
````
(ns test-app.core
  (:require [test-app.main :as main]))
````
from core.cljs? I am just looking for a pattern.

**Comment by tokomakoma123** [comment] 2015-02-05 00:00
>>This seems similar to #83 .
Yes, it looks similar. The code is like.
```clj
(ns test-app.core
  (:require [om.core :as om :include-macros true]
            [om.dom :as dom :include-macros true]))

(defonce app-state (atom {:text "Hello Chestnut!"}))

(defn main []
  (om/root
    (fn [app owner]
      (reify
        om/IRender
        (render [_]
          (dom/h1 nil (:text app)))))
    app-state
    {:target (. js/document (getElementById "app"))}))
```

**Comment by plexus** [comment] 2015-02-05 10:01
Do you get the same problem with master? To try this clone the chestnut repo, cd into it, the `lein install`. If you do `lein new chestnut test-app --snapshot` you'll have the latest master.

**Comment by samedhi** [comment] 2015-02-05 23:34
I did as you asked; this isn't a issue at all on --snapshot .

BTW, the Clojure error messages at the bottom of the screen in the browser are sweet.

**Comment by plexus** [comment] 2015-02-06 12:52
Cool, closing it then.

**Closed by plexus** 2015-02-06 12:52 UTC

**Comment by skrat** [comment] 2015-02-21 17:55
I have a similar same problem, with `(browser-repl)`. Weasel runs `cljs.repl/analyze-source` and it [throws](https://gist.github.com/skrat/49f3d17a2973f6d87389). There's nothing wrong with those source files, building with cljsbuild just works, no warnings. When I drop requiring that namespace, it complains about another one, same error.

**Comment by loganmhb** [comment] 2015-03-13 15:42
I get this problem still, even with locally installed master and --snapshot. Steps I took:

Clone master and lein install.
    lein new chesnut test-app
    cd test-app
    lein repl
    (run)
    => WARNING: No such namespace: test-app.core at line 1 env/dev/cljs/test-app/main.cljs

Any pointers on what the source of this might be? I'm happy to do some digging but not sure where to start.

**Comment by plexus** [comment] 2015-03-14 10:34
@loganmhb can you paste the full output please? That warning can be caused by any number of things. There's usually a hint higher up.

**Comment by loganmhb** [comment] 2015-03-16 14:51
Here is the full output:

test-app.server=> (run)
Figwheel: Starting server at http://localhost:3449
Figwheel: Serving files from '(resources)/public'
2015-03-16 09:49:51.991:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-03-16 09:49:52.024:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:10555
Starting web server on port 10555 .
#<Server org.eclipse.jetty.server.Server@5337ac82>
test-app.server=> Compiling "resources/public/js/app.js" from ["env/dev/cljs" "src/cljs"]...
WARNING: No such namespace: test-app.core at line 1 env/dev/cljs/test_app/main.cljs
Successfully compiled "resources/public/js/app.js" in 18.782 seconds.
notifying browser that file changed:  /js/app.js
notifying browser that file changed:  /js/out/goog/deps.js
notifying browser that file changed:  /js/out/test_app/main.js
notifying browser that file changed:  /js/out/test_app/core.js

**Comment by plexus** [comment] 2015-03-16 14:54
Seems like a harmless warning. Do you see the "Hello Chestnut" when browsing to [http://localhost:10555](http://localhost:10555)?

**Comment by loganmhb** [comment] 2015-03-16 15:04
Yes, the app seems to run fine despite the warning. I am currently trying to replicate a problem with a similar warning that caused a fatal error, but they may be unrelated -- just wanted to make sure this out-of-the-box warning was known and/or not an issue. If I succeed in replicating the other problem and it still seems like a Chestnut issue I can open a new one.

Thanks!

**Comment by plexus** [comment] 2015-03-16 15:09
Yeah this warning often pops up. I'm not sure what causes it, might just be a Clojurescript issue.

@annapawlicka @martinklepsch you have any idea where that warning comes from?

**Comment by swannodette** [comment] 2015-03-16 15:40
```
env/dev/cljs/test-app/main.cljs
```

Is an invalid classpath location for that file.

Needs to be:

```
env/dev/cljs/test_app/main.cljs
```

Chestnut should be doing the sanitation of the path based on the project name for you. The mies project does this if people are looking for a reference.

**Comment by plexus** [comment] 2015-03-16 15:43
Thank you for pointing that out! That bug must have been in Chestnut since forever. I'll fix it.

**Comment by plexus** [comment] 2015-03-16 16:10
This isn't an issue on master, in which case it also shouldn't be an issue in the current stable release (0.7.0), since nothing has changed to the rendering code since then.

```
$ lein new sesame-seed
$ find sesame-seed -name core.cljs
sesame-seed/src/cljs/sesame_seed/core.cljs
```

**Comment by plexus** [comment] 2015-03-16 16:13
I probably spoke to soon, need to dig a bit more. The directories are correctly sanitized, so must be something else going on.

**Comment by plexus** [comment] 2015-03-16 16:17
Note that after upgrading Clojurescript compilation of that file fails completely without any hints to why... insights would be greatly appreciated. I'll mail a dozen Chestnut stickers to whomever supplies the tip that lets me solve this :)

https://github.com/plexus/chestnut/issues/106
