### ISSUE TITLE
chestnut lein template is not working in Windows 

### ISSUE THREAD

**Issue by skprasadu** [plexus/chestnut#104] opened 2015-03-10 04:19 UTC
In Windows, when you create a new chestnut project from template like,

    lein new chestnut <name>

and do a,

    lein repl
    (run) 

It throws an url exception like,

    InvalidPathException Illegal char <:> at index 2

On further troubleshooting, this is a side effect of enlive [bug#92](https://github.com/cgrand/enlive/issues/92) .

This is already fixed and is not pushed into clojars.. for now git clone enlive code and install enlive do,

    lein install 

And repeat the earlier steps.

Hope this helps.

**Comment by plexus** [comment] 2015-03-10 09:11
I've marked it as an upstream issue. We'll leave this issue open until it's fixed upstream in case others come looking here what the problem is.

**Comment by vojd** [comment] 2015-06-30 12:09
@skprasadu Thanks for the explanation and solution to this problem.

**Comment by slester** [comment] 2015-07-20 14:37
@plexus Can be closed as well!

**Closed** 2015-07-20 16:08 UTC
Labels: upstream issue
