### ISSUE TITLE
Can't change/establish root binding of: *cljs-repl-options* with set

### ISSUE THREAD

**Issue by kevincolyar** [plexus/chestnut#109] opened 2015-03-24 16:18 UTC
Created a new project but trying to start the browser repl results in an error:

```sh
lein new chestnut foo
lein repl
````
```clojure
foo.server=> (run)
Figwheel: Starting server at http://localhost:3449
Figwheel: Serving files from '(resources)/public'
2015-03-24 09:13:53.298:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-03-24 09:13:53.328:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:10555
Starting web server on port 10555 .
#<org.eclipse.jetty.server.Server@692a525d org.eclipse.jetty.server.Server@692a525d>
foo.server=> Compiling "resources/public/js/app.js" from ["env/dev/cljs" "src/cljs"]...
WARNING: No such namespace: foo.core at line 1 env/dev/cljs/foo/main.cljs
Successfully compiled "resources/public/js/app.js" in 8.869 seconds.
notifying browser that file changed:  /js/app.js
notifying browser that file changed:  /js/out/goog/deps.js
notifying browser that file changed:  /js/out/foo/main.js
notifying browser that file changed:  /js/out/foo/core.js

foo.server=> (browser-repl)
java.lang.IllegalStateException: Can't change/establish root binding of: *cljs-repl-options* with set
```

**Comment by plexus** [comment] 2015-03-24 16:28
Can you please create a repo of your app?

**Comment by kevincolyar** [comment] 2015-03-24 16:32
https://github.com/kevincolyar/chestnut-test

**Comment by plexus** [comment] 2015-03-24 16:46
Unfortunately I can't reproduce your issue, this is what it looks like for me

```
nREPL server started on port 32849 on host 127.0.0.1 - nrepl://127.0.0.1:32849
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

foo.server=> (run)
Figwheel: Starting server at http://localhost:3449
Figwheel: Serving files from '(resources)/public'
2015-03-24 17:42:22.157:INFO:oejs.Server:jetty-7.6.13.v20130916
2015-03-24 17:42:22.237:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:10555
Starting web server on port 10555 .
#<Server org.eclipse.jetty.server.Server@67d639a3>
foo.server=> Compiling "resources/public/js/app.js" from ["env/dev/cljs" "src/cljs"]...
WARNING: No such namespace: foo.core at line 1 env/dev/cljs/foo/main.cljs
Successfully compiled "resources/public/js/app.js" in 33.316 seconds.
notifying browser that file changed:  /js/app.js
notifying browser that file changed:  /js/out/goog/deps.js
notifying browser that file changed:  /js/out/foo/main.js
notifying browser that file changed:  /js/out/foo/core.js


foo.server=> (browser-repl)
<< started Weasel server on ws://0.0.0.0:9001 >>
Type `:cljs/quit` to stop the ClojureScript REPL
foo.core
foo.core=> app-state
#<Atom: {:text "Hello Chestnut!"}>
nil
foo.core=> 
```

So the question is, what in your environment is different... What's your `java -version`? @swannodette do you have any suggestions?

**Comment by plexus** [comment] 2015-03-24 16:46
If you have anything in `~/.lein/profiles.clj`, could you try with an empty `~/.lein/profiles.clj` instead?

**Comment by kevincolyar** [comment] 2015-03-24 16:52
Ah, that was it.  Had the following in my profiles.clj:

```clojure
{:user {:plugins [
                  [venantius/ultra "0.1.9"]
                  [jonase/eastwood "0.2.1"] ;; Lint tool
                  ]
        :ultra {:color-scheme :solarized_dark}}}

```

**Comment by plexus** [comment] 2015-03-24 16:54
Ok, glad that solves it. I'm closing this now. What you could do is figure out which dependency exactly causes issues and report the issue there.

**Closed by plexus** 2015-03-24 16:54 UTC

**Comment by kevincolyar** [comment] 2015-03-24 17:00
Looks like it was:

```clojure
[venantius/ultra "0.1.9"]
```

Upgrading to 0.3.3 seems to have fixed it.

Thanks for the help!

**Comment by edbond** [comment] 2015-03-25 15:17
Yes, I had problems with previous version of ultra (< 0.3) too.
